// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjnawesyghqidxcfmtqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqbmF3ZXN5Z2hxaWR4Y2ZtdHFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MjU3MzQsImV4cCI6MjA2OTMwMTczNH0.m1-42ageY8db_9r-_UD4zTsLbbVKd3D5wa71nS-hpvQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});